server:
  port: 8083
spring:
  datasource:
    url: jdbc:h2:mem:vehicledb
    username: sa
    password: 123456
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  application:
    name: vehicle-service
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/