apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-service
spec:
  selector:
    matchLabels:
      app: eureka-service
  replicas: 1
  template:
    metadata:
      labels:
        app: eureka-service
    spec:
      containers:
        - name: eureka-service
          image: brunorudy1/eureka:latest
          ports:
            - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-service
spec:
  type: NodePort
  ports:
    - port: 8761
      targetPort: 8761
      nodePort: 31761
  selector:
    app: eureka-service