apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: vehicle-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vehicle-service
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50